#!/usr/bin/env bash
# Installs nginx web server and configure index file:
#+    Listens on port 80
#+    Returns a page containing "Hello World!" when queried at the root with a
      curl GET request

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
