#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”

sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
